export default [
  {
    selector: 'node',
    style: {
      width: 70,
      color: '#fff',
      label: 'data(name)',
      shape: 'rectangle',
      'font-size': 7,
      'font-weight': 'bold',
      'text-max-width': 60,
      'text-valign': 'center',
      'background-color': '#438cd4',
      'text-wrap': 'ellipsis',
    },
  },
  {
    selector: ':parent',
    style: {
      'background-color': '#fff',
      'background-opacity': 0.3,
      'text-valign': 'top',
      'text-halign': 'center',
      'border-style': 'dashed',
      'text-margin-y': -3,
    },
  },
  {
    selector: 'edge',
    style: {
      width: 0.2,
      label: 'data(name)',
      'font-size': 4,
      'font-weight': 'bold',
      'text-background-color': '#f0f2f5',
      'text-background-opacity': 1,
      'color': '#707070',
      'target-arrow-shape': 'triangle',
      'arrow-scale': 0.4,
      'line-color': '#707070',
      'line-style': 'dashed',
      'line-dash-pattern': [4, 4],
      'line-cap': 'square',
      'target-arrow-color': '#707070',
      'curve-style': 'straight',
      'text-max-width': 80,
      'text-wrap': 'wrap',
    },
  },
];
